package ru.shypitsa.recipeapp

const val KEY_IN_BUNDLE_FOR_ARG_CATEGORY_ID = "ARG_CATEGORY_ID"
const val KEY_IN_BUNDLE_FOR_ARG_CATEGORY_NAME = "ARG_CATEGORY_NAME"
const val KEY_IN_BUNDLE_FOR_ARG_CATEGORY_IMAGE_URL = "ARG_CATEGORY_IMAGE_URL"
const val KEY_IN_BUNDLE_FOR_ARG_RECIPE = "ARG_RECIPE"
